config/routes.rb
J0bD::Application.routes.draw do

  get 'employers/favoritelist' => 'employers#favoriteList'

  resources :github_repos
  resources :employees
  resources :stack_tags
  resources :dribbbles, only: [:create]
  resources :linkedins, only: [:create, :show]
  resources :favorites, only: [:create, :index]

  get 'auth/linkedin/callback', to: 'linkedins#create'

  resources :employers, except: [:create]
  delete '/employers' => 'employers#destroy'

  get 'auth/:provider/callback', to: 'github_accounts#create'
  get 'auth/failure', to: redirect('/')
  delete 'signout', to: 'github_accounts#destroy', as: 'signout'

  resources :github_accounts, only: [:create, :destroy]

  get "employees/update"
  get "employees/new"
  get "page/landing_page"
  root 'page#landing_page'
  post 'employees/create' => 'employees#create'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_one :primary_stats
  has_one :github_account
  has_one :dribbble
  has_one :stack_overflow_account
  has_one :linked_in
  has_many :favorites # Need this?
  has_many :favorite_employers, through: :favorites, source: :employer

  # Create github account
  def create_github(auth)
    self.create_github_account({
      provider: auth['provider'],
      uid: auth['uid'],
      username: auth.extra.raw_info.login,
      oauth_token: auth.credentials.token
      })
  end

  # Modify top skills using all datas
  def skills_stats_modifier
    # Modify stats using StackOverflow's top_tags_score
    top_stats = self.github_top_skills

    if self.stack_overflow_account
      top_tags_score = self.calculate_top_tags_score
      # Hard code for now... out of time.
      ruby_tags = ['ruby', 'ruby-on-rails']
      javascript_tags = ['jquery', 'angularjs', 'nodejs']
      css_tags = ['html', 'css3', 'layout', 'haml', 'markdown']

      top_tags_score.each do |tag|
        if ruby_tags.include?(tag[:tag_name])
          top_stats[:ruby] += tag[:score]
        elsif javascript_tags.include?(tag[:tag_name])
          top_stats[:javascript] += tag[:score]
        elsif css_tags.include?(tag[:tag_name])
          top_stats[:css] += tag[:score]
        end
      end
    end

    # Modify stats using Dribbble
    if self.dribbble
      top_stats[:css] += self.calculate_dribbble_boost
    end

    # Modify stats using LinkedIn
    # headline: boost overall by %
    # industry: boost overall by %?
    # language: boost overall by %?
    # skills:   boost by ?????
    # -break it down to skills found?????
    # education: boost overall by %?
    # positions: boost by ??????
    # -break it down to skills found?

    # Simple LinkedIn solution for now...
    if self.linked_in
      linked_in_boost = self.calculate_linkedin_boost
      top_stats.each do |key, value|
        top_stats[key] = (value * linked_in_boost).to_i
      end
    end

    # Create / update employee's primary stats after calculation
    if self.primary_stats.nil?
      self.create_primary_stats(top_stats)
    else
      self.primary_stats.update(top_stats)
    end
  end

  # Get top skills from Github's data
  def github_top_skills
    ruby = javascript = coffeescript = css = php = 0
    allRepos = self.github_account.github_repos
    allRepos.each do |repo|
      ruby += repo.Ruby.to_i if repo.Ruby
      javascript += repo.JavaScript.to_i if repo.JavaScript
      coffeescript += repo.CoffeeScript.to_i if repo.CoffeeScript
      css += repo.CSS.to_i if repo.CSS
      php += repo.PHP.to_i if repo.PHP
    end
    repos = {ruby: ruby, javascript: javascript, coffeescript: coffeescript, css: css, php: php}

    # Save top 4 skills
    count = 0
    sorted_repos = repos.values.sort
    while repos.length > 4
      remove_key = repos.key(sorted_repos[count])
      repos.delete(remove_key)
      count += 1
    end

    return repos
  end

  # Get all tags related to top Github skills
  def top_tags
    related_tags = []
    all_tags = stack_overflow_account.stack_tags
    all_repos = github_top_skills.keys.map(&:to_s)

    # Add tags that are similar to any matched tag in all_repos to all_repos
    all_repos.each do |repo|
      case repo
      when 'ruby'
        all_repos.push(['ruby-on-rails'])
      when 'javascript'
        all_repos.push(['jquery'])
      when 'css'
        all_repos.push(['html', 'css3', 'layout', 'haml', 'markdown'])
      end
      all_repos.flatten!
    end

    all_tags.each do |tag|
      if all_repos.include?(tag.top_tag_name)
        related_tags.push({
          tag_name: tag.top_tag_name,
          answer_count: tag.answer_count,
          answer_score: tag.answer_score,
          question_count: tag.question_count,
          question_score: tag.question_score
          })
      end
    end
    related_tags
  end

  # Calculate top_tags overall score, only answers for now.
  def calculate_top_tags_score
    tags_score = []

    # Reputation weight
    reputation = stack_overflow_account.reputation

    top_tags.each do |tag|

      # Answer_score / answer_count * 10%
      multiplier = (tag[:answer_score] / tag[:answer_count]) * 0.02

      # Answer_score * multiplier * answer_count * answer_score + reputation
      score = ((tag[:answer_score] * multiplier * tag[:answer_count]) * tag[:answer_score]).round + reputation
      tags_score.push({tag_name: tag[:tag_name], score: score})
    end
    # Hacky way to remove dupls... check out why later
    tags_score.uniq

  end

  # Calculate Dribbble overall boost to front end stats
  def calculate_dribbble_boost
    my_dribbble = self.dribbble
    shots_score = my_dribbble.shots_count * 50
    likes_score = (my_dribbble.likes_count * 0.25).to_i
    likes_received_score = my_dribbble.likes_received_count
    rebounds_score = my_dribbble.rebounds_count * 100
    rebounds_received_score = my_dribbble.rebounds_received_count.to_i * 100

    dribbble_boost = (shots_score + likes_score + likes_received_score + rebounds_score + rebounds_received_score) * 100
  end

  # Calculate LinkedIn overall boost
  def calculate_linkedin_boost
    # Set score/weight for headline
    headline_score = calculate_LI_headline

    # Set score/weight for relevant industry?
    industry_score = calculate_LI_industry

    # Set score/weight for # of spoken languages?
    language_score = calculate_LI_languages

    # Set score/weight for relevant skills in skills list?
    skills_score = calculate_LI_skills

    # Calculate all data points to get overall general info score

    # Set score/weight for education
    education_score = calculate_LI_education
    # calculate all data points to get overall education score

    # Set score/weight at time employed at position
    # Set score/weight for relevant skill(s) in position summary
    # Set score/weight for relevant title in position
    positions_score = calculate_LI_positions

    # Calculate all data points to get overall position score
    # Test hash to view datas for now... should return a % modifier
    all_scores = {headline_score: headline_score, industry_score: industry_score, language_score: language_score, skills_score: skills_score, education_score: education_score, positions_score: positions_score}

    total_percentage_boost = 0;
    all_scores.values.each do |score|
      total_percentage_boost += (score * 0.001)
    end
    total_percentage_boost
  end

  ########## LinkedIn Score System Methods #######
  # Takes a list of words and string, return matched counts
  def words_scanner(words, text)
    matched_words = []
    return matched_words.length if text.nil?

    words.each do |word|
      if text.downcase.include?(word)
        matched_words.push(word)
      end
    end
    matched_words.length
  end

  # LinkedIn score for headline or Position title
  def calculate_LI_headline
    headlines = ['web designer', 'web designer', 'developer', 'web developer', 'Front End developer', 'Back End Developer', 'web architect']

    seniority_boost = ['senior', 'lead', 'sr']

    headlines_score = words_scanner(headlines, linked_in.headline) * 100
    seniority_score = words_scanner(seniority_boost, linked_in.headline) * 150

    total_stats_boost = headlines_score + seniority_score
  end

  # LinkedIn score for industry
  def calculate_LI_industry
    industries = ['civil engineering', 'computer games', 'computer hardware', 'computer networking', 'computer software', 'design', 'fine art', 'graphic design', 'information technology and services', 'internet', 'machinery', 'media production', 'mechanical engineering']

    industry_score = words_scanner(industries, linked_in.industry) * 100
  end

  # LinkedIn score for spoken languages
  def calculate_LI_languages
    linked_in.languages.split(',').count * 30
  end

  # LinkedIn score for skills
  def calculate_LI_skills
    top_skills = github_top_skills.keys.map(&:to_s)
    words_scanner(top_skills, self.linked_in.skills) * 20
  end

  # LinkedIn score for educations
  def calculate_LI_education
    relevant_fields = ['computer science', 'digital communication', 'media multimedia', 'computer and information sciences', 'artifical intelligence', 'information technology', 'informatics', 'computer and information sciences', 'computer programming', 'data processing', 'information science', 'computer systems', 'computer graphics', 'engineering', 'computer software', 'software engineering', 'computer engineering', 'computer hardware']

    bachelor_degree = ['bachelor', 'ba']
    master_degree = ['master', 'ma']

    my_degree = linked_in.educations.map(&:degree).compact.join(' ')
    my_field = linked_in.educations.map(&:field_of_study).compact.join(' ')

    # Field of study score
    field_score = words_scanner(relevant_fields, my_field)

    # Degree score(s)
    ba_score = words_scanner(bachelor_degree, my_degree)
    ma_score = words_scanner(master_degree, my_degree)

    education_score = (ba_score * 50) + (ma_score * 100) + (field_score * 100)

    # TODO: Bachelor and BA are credited if both included in degree.
  end

  # LinkedIn score for work experience(positions)
  def calculate_LI_positions
    titles = ['web designer', 'web designer', 'developer', 'web developer', 'Front End developer', 'Back End Developer', 'web architect']
    seniority_boost = ['senior', 'lead', 'sr']
    companies = ['google', 'facebook', 'twitter', 'linkedin']
    relevant_skills = self.top_tags.map {|tag| tag[:tag_name]}

    titles_score = 0
    summary_score = 0
    experience_score = 0
    company_score = 0

    self.linked_in.positions.each do |position|
      # Calculate score for position's title
      title = words_scanner(titles, position.title) * 10
      seniority = words_scanner(seniority_boost, position.title) * 30
      titles_score += (title + seniority)

      # Calculate score for position's summary

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def index
    @employees = Employee.all
  end

  def update
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new
    redirect_to "/"
  end

  def show
    @employee = Employee.find(params[:id])
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/index.html.erb
  <h2>Employees Data</h2>
<% if current_employee.github_account %>
  <h3>Top Stats</h3>
  Ruby: <%= current_employee.primary_stats.ruby %> <br>
  Javascript: <%= current_employee.primary_stats.javascript %> <br>
  CSS: <%= current_employee.primary_stats.css %> <br>
  Coffeescript: <%= current_employee.primary_stats.coffeescript %>

  <h3>Top Github Skills</h3>
  <% current_employee.github_top_skills.each do |key, value| %>
    <%= key %> : <%= value %> <br>
  <% end %>

  <h3></h3>


  <h3>Calculated SO Top Tags Score</h3>
  <table>
    <thead>
      <th>Tag</th>
      <th>Score</th>
    </thead>

  <% if current_employee.stack_overflow_account %>
  <% current_employee.calculate_top_tags_score.each do |tag| %>
    <tr>
      <td><%= tag[:tag_name] %></td>
      <td><%= tag[:score] %></td>
    </tr>
  <% end %>
  <% end %>
  </table>
  <h3>Related SO Stats</h3>

  <table>
    <thead>
      <th>Tag</th>
      <th>Answer Count</th>
      <th>Answer Score</th>
      <th>Question Count</th>
      <th>Question Score</th>
    </thead>
  <% if current_employee.stack_overflow_account %>
  <% current_employee.top_tags.each do |tag| %>
    <tr>
      <td><%= tag[:tag_name] %></td>
      <td><%= tag[:answer_count] %></td>
      <td><%= tag[:answer_score] %></td>
      <td><%= tag[:question_count] %></td>
      <td><%= tag[:question_score] %></td>
    </tr>
  <% end %>
  <% end %>
<% end %>
  </table>

  <!-- Show all Github repositories -->
  <%= @employee.github_account.username %>'s Repositories
  <table>
    <thead>
      <th>Name</th>
      <th>Ruby</th>
      <th>JavaScript</th>
      <th>CoffeeScript</th>
      <th>CSS</th>
      <th>PHP</th>
      <th>Created_at</th>
      <th>Updated_at</th>
    </thead>

    <% @employee.github_account.github_repos.each do |repo| %>
      <tr>
        <td><%= repo.name %></td>
        <td><%= repo.Ruby %></td>
        <td><%= repo.JavaScript %></td>
        <td><%= repo.CoffeeScript %></td>
        <td><%= repo.CSS %></td>
        <td><%= repo.PHP %></td>
        <td><%= repo.created_at.to_formatted_s(:long) %></td>
        <td><%= repo.updated_at.to_formatted_s(:long) %></td>
      </tr>
    <% end %>
  </table>

  <!-- Show employee's stackoverflow data if they have an account connected -->
  <% if current_employee.stack_overflow_account %>
  <h2>StackOverflow Data</h2>
    <h2>ID: <%= current_employee.stack_overflow_account.id %> | Rep: <%=current_employee.stack_overflow_account.reputation %> | Badges: <%= current_employee.stack_overflow_account.badge_counts %></h2>
    <table>
      <thead>
        <th>Tag Name</th>
        <th>Answer Count</th>
        <th>Answer Score</th>
        <th>Question Count</th>
        <th>Question Score</th>
      </thead>

      <% current_employee.stack_overflow_account.stack_tags.each do |tag| %>
        <tr>
          <td><%= tag.top_tag_name %></td>
          <td><%= tag.answer_count %></td>
          <td><%= tag.answer_score %></td>
          <td><%= tag.question_count %></td>
          <td><%= tag.question_score %></td>
        </tr>
      <% end %>
    </table>
  <% end %>


  <!-- Show employee's Dribbble data if they have an account connected -->
  <% if current_employee.dribbble %>
  <h2>Dribbble Data</h2>
    <table>
      <thead>
        <th>Shots Count</th>
        <th>Likes Count</th>
        <th>Likes Received Count</th>
        <th>Rebounds Count</th>
        <th>Rebounds Received Count</th>
      </thead>

        <tr>
          <td><%= current_employee.dribbble.shots_count %></td>
          <td><%= current_employee.dribbble.likes_count %></td>
          <td><%= current_employee.dribbble.likes_received_count %></td>
          <td><%= current_employee.dribbble.rebounds_count %></td>
          <td><%= current_employee.dribbble.rebounds_received_count %></td>
        </tr>
    </table>
  <% end %>

  <% if current_employee.linked_in %>
    <h2>LinkedIn Data</h2>
    <h2>General Information</h2>
    <table>
      <thead>
        <th>Name</th>
        <th>Headline</th>
        <th>Industry</th>
        <th>Interests</th>
        <th>Spoken Languages</th>
        <th>Skills</th>
      </thead>

      <tr>
        <td><%= current_employee.linked_in.first_name %></td>
        <td><%= current_employee.linked_in.headline %></td>
        <td><%= current_employee.linked_in.industry %></td>
        <td><%= current_employee.linked_in.interests %></td>
        <td><%= current_employee.linked_in.languages %></td>
        <td><%= current_employee.linked_in.skills %></td>
      </tr>
    </table>

    <h2>Positions</h2>
    <table>
      <thead>
        <th>Title</th>
        <th>Summary</th>
        <th>Is Current</th>
        <th>Start Date</th>
        <th>End Date</th>
      </thead>

    <% current_employee.linked_in.positions.each do |position| %>
      <tr>
        <td><%= position.title %></td>
        <td><%= position.summary %></td>
        <td><%= position.is_current %></td>
        <td><%= position.start_date %></td>
        <td><%= position.end_date %></td>
      </tr>
    <% end %>
    </table>

    <h2>Education</h2>
    <table>
      <thead>
        <th>Degree</th>
        <th>Field of Study</th>
        <th>School Name</th>
      </thead>

    <% current_employee.linked_in.educations.each do |education| %>
      <tr>
        <td><%= education.degree %></td>
        <td><%= education.field_of_study %></td>
        <td><%= education.school_name %></td>
      </tr>
    <% end %>
    </table>
  <% end %>
</div>

app/views/employees/new.html.erb
<h1>Employees#new</h1>
<p>Find me in app/views/employees/new.html.erb</p>

app/views/employees/show.html.erb
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>

<div id="show-page">

        <!-- PROFILE CARD -->
  <div class="profile-card">
    <div class="prof-pic"></div>
  <div class="badge-container">
  <%= current_employee.github_account.username %>
    <!-- <div class="prof-badges"></div>
    <div class="prof-badges"></div>
    <div class="prof-badges"></div>
    <div class="prof-badges"></div> -->
  </div>
  <div class="text-container">
    <div class="prof-text"></div>
    <div class="prof-text"></div>
    <div class="prof-text"></div>
    <div class="prof-text"></div>
  </div>
  <div class="panel-container">
    <div class="prof-panel">Github : Connected</div>
    <div class="prof-panel">
  <!-- STACK OVER FLOW -->
    <% if current_employee.stack_overflow_account %>
        <strong>Stackoverflow: Connected</strong> <br />
      <% else %>
        <!-- Enter StackOverflow's ID to save info to database -->
        <%= form_tag "/stack_tags", method: 'POST' do %>
          <%= text_field_tag :stackoverflow_id, params[:stackoverflow_id] %>
          <%= submit_tag "Add StackOverflow" %>
        <% end %>
      <% end %>
      </div>
    <div class="prof-panel">
            <!-- LinkedIn -->
      <% if current_employee.linked_in %>
        LinkedIn: Connected <br>
      <% else %>
        <div id="linkedin"><%= link_to "Sign up with LinkedIn", "/auth/linkedin" %></div>
      <% end %>
    </div>
    <div class="prof-panel">
          <!-- Dribble -->
      <% if current_employee.dribbble %>
        <strong>Dribbble: Connected</strong> <br />
      <% else %>
        <%= form_tag "/dribbbles", method: 'POST' do %>
          <%= text_field_tag :dribbble_username, params[:dribbble_username] %>
          <%= submit_tag "Add Dribbble" %>
        <% end %>
      <% end %>
    </div>
    <%= button_to "Save", employees_path, :method=> "skills_stats_modifier", class:"btn btn-primary btn-sm" %>
    <%#= current_employee.stack_overflow_account && current_employee.linked_in && current_employee.dribbble ? (button_to "Save", employees_path, :method=> "skills_stats_modifier", class:"btn btn-primary btn-sm") : ("Link all accounts to save") %>
    </div>
  </div>
</div>

app/views/employees/update.html.erb
<h1>Employees#update</h1>
<p>Find me in app/views/employees/update.html.erb</p>